### ISSUE TITLE
Full Deploy Example?

### ISSUE THREAD

**Issue by shelldandy** [tshamz/gulp-shopify-upload-with-callbacks#1]
Please 😢

**Comment by tshamz** [comment]
are we talking, "fully deploy" meaning deploy all files to a particular Shopify theme?

**Comment by shelldandy** [comment]
Yes, that exactly. Like a cold full deploy.

**Comment by shelldandy** [comment]
For example to integrate in a CI situation, push repo, build and deploy to a certain theme, receive bacon 😄

**Comment by tshamz** [comment]
hmmmmmmmm, tbh we use a totally separate service to do our deployments from scratch (http://beanstalkapp.com) and so we don't have much use for this, but if you opened a pull request with this in it I would more than likely merge it in.

**Comment by shelldandy** [comment]
Thanks a lot!

I ended up going with `gulp-shopify-upload` since it also has a purge option really good for first time deletion of the default shopify theme

https://github.com/Pixel2HTML/shopify-skeleton/blob/master/src/app/templates/gulp/tasks/deploy.js

I also noted I was writing the src string wrong but i realized it too late and had already switched to the other plugin, so maybe theres nothing wrong with this one to begin with 😄 

Thanks for all the effort and I hope you give the tool i made a spin 😛

**Comment by tshamz** [comment]
npnp, sorry it took me so long to get back to you. This tool really isn't in active development and tbh, we don't even use the callback portion of it anymore (although I like the feeling of just knowing it's there 😊). The `gulp-shopify-upload` is the actually where this plugin came from, so i'd trust it with my life. I'll be sure to check out your tool when i get a chance!
