### ISSUE TITLE
Not a valid theme id

### ISSUE THREAD

**Issue by coreyharrison** [tshamz/gulp-shopify-upload-with-callbacks#2]
Hi there!
I've found my way here after going through the Shopify Partner training for Setting up a Shopify Development Environment. I'm getting this error: 
`Error in plugin "gulp-shopify-upload-with-callbacks"
Message:
    Error, not a valid theme id!` 
when I run `gulp` or `gulp upload`. I have my `.env` in the root of my project with my `gulpfile.js`.
My API settings are correct as is the theme id and store url. Seems pretty straight forward, but I'm unable to workout why the theme id it coming out as invalid.

Any pointers would be very much appreciated.

Thanks!

**Comment by tshamz** [comment]
hey, i just bumped a new version of the plugin that should have fixed this. lmk if you're still running into the issue though.

**Comment by coreyharrison** [comment]
Cheers!
